#+title: config.org
#+startup: fold
#+property: header-args:emacs-lisp :results silent

* Base

#+begin_src emacs-lisp
;;; config.el -*- lexical-binding: t; -*-

(setenv "PATH"
        (concat
          (getenv "EMACS_PATH_PREFIX") path-separator
          (getenv "PATH")))
#+end_src

** Constants

Let's define some constants we'll use throughout our configuration. Yeah, Doom
already define those, but we want to keep all constants as ~*<name>*~.

*** Operating System

#+begin_src emacs-lisp
(defconst *is-macos* IS-MAC)
(defconst *is-linux* IS-LINUX)
#+end_src

*** Emacs version

#+begin_src emacs-lisp
(defconst *is-emacs-28* EMACS28+)
(defconst *is-emacs-29* EMACS29+)
#+end_src

** Performance

*** Update UI less frequently.

#+begin_src emacs-lisp
(setq idle-update-delay 1.0
      jit-lock-defer-time 0)
#+end_src

*** Pixel scroll

In Emacs > 29, we can use Po Lu's ~pixel-scroll-precision-mode~ to get a faster
and better scrolling.

#+begin_src emacs-lisp
(when *is-emacs-29*
    (pixel-scroll-precision-mode))
#+end_src

** Behavior
*** UTF-8 by default

Emacs is very conservative about assuming encoding. Everything is utf-8 these days,
lets have that as the default.

#+begin_src emacs-lisp
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(set-file-name-coding-system 'utf-8)
(set-clipboard-coding-system 'utf-8)
(set-buffer-file-coding-system 'utf-8)
#+end_src

*** Final EOL
Always set a EOL at the end of files.

#+begin_src emacs-lisp
(setq require-final-newline t)
#+end_src

* Behavior

** Language Server Protocol (LSP)

Although Doom already handles a bunch of stuff for us, we need to change some
things.

First, we install everything via Nix, so =lsp-mode= don't need to asks us anything.

#+begin_src emacs-lisp
(setq lsp-enable-suggest-server-download *is-macos*)
#+end_src

Now, we improve the performance of =lsp-mode=.

#+begin_src emacs-lisp
(setq lsp-use-plists t
      lsp-idle-delay 1
      lsp-log-io nil
      read-process-output-max (* 10 1024 1024))
#+end_src

*** Hover

#+begin_src emacs-lisp
(setq lsp-ui-doc-position 'top
      lsp-ui-doc-max-height 20
      lsp-ui-doc-delay 0.5
      lsp-ui-doc-show-with-cursor nil
      lsp-ui-doc-show-with-mouse t
      lsp-ui-doc-header t
      lsp-ui-doc-use-childframe nil
      lsp-ui-doc-use-webkit t)
#+end_src

*** Semantic Highlighting

#+begin_src emacs-lisp
(setq lsp-semantic-tokens-enable t
      lsp-semantic-tokens-honor-refresh-requests nil)
#+end_src

*** Code Lens

#+begin_src emacs-lisp
(setq lsp-lens-place-position 'above-line)
#+end_src

*** UI
**** Sideline

#+begin_src emacs-lisp
(setq lsp-ui-sideline-enable t
      lsp-ui-sideline-diagnostics t
      lsp-ui-sideline-hover nil
      lsp-ui-sideline-update-mode #'line)
#+end_src

**** Peek

#+begin_src emacs-lisp
(setq lsp-ui-peek-enable t)
#+end_src

**** Imenu

#+begin_src emacs-lisp
(setq lsp-ui-imenu-kind-position 'left)
#+end_src

**** Breadcrumbs

#+begin_src emacs-lisp
(setq lsp-headerline-breadcrumb-enable t
      lsp-headerline-breadcrumb-segments '(file symbols))
#+end_src

*** Disable Servers

#+begin_src emacs-lisp
(setq lsp-disabled-clients '((typescript-mode . deno)))
#+end_src

* Appearance
** Text
*** Constants

First, some sizes.

#+begin_src emacs-lisp
(defconst *line-spacing* 0.25)

(defconst *text-font-height* 14)
(defconst *ui-font-height* 13)
#+end_src

Now, the fonts we will use. These are passed via environment variables
via our Nix module.

#+begin_src emacs-lisp
(defconst *fixed-pitch-font* "Maple Mono NF"
    "Font used for monospaced text.")

(defconst *variable-pitch-font* "Noto Sans"
    "Font used for variable text.")

(defconst *serif-font* "Noto Serif"
    "Font used for serif text.")

(defconst *unicode-font* "Latin Modern Math"
    "Font used to display unicode symbols.")
#+end_src

*** Font faces

Let's start changing the global Doom font faces.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family *fixed-pitch-font* :size *text-font-height*)
      doom-variable-pitch-font (font-spec :family *variable-pitch-font* :size *text-font-height*)
      doom-serif-font (font-spec :family *serif-font* :size *text-font-height*)
      doom-unicode-font (font-spec :family *unicode-font* :size *text-font-height*)
      doom-font-increment 1)
#+end_src

Now, the modeline:

#+begin_src emacs-lisp
(custom-set-faces
  `(mode-line ((t (:font ,doom-variable-pitch-font)))))
#+end_src

~org-mode~...

#+begin_src emacs-lisp
(custom-set-faces!
  '(org-document-title :height 1.2)
  '(org-level-1 :weight extra-bold :height 1.45)
  '(org-level-2 :weight bold :height 1.35)
  '(org-level-3 :weight bold :height 1.2)
  '(org-level-4 :weight semi-bold :height 1.00)
  '(org-level-5 :weight semi-bold :height 1.00)
  '(org-level-6 :weight semi-bold :height 1.00)
  '(org-level-8 :weight semi-bold)
  '(org-level-9 :weight semi-bold))

;; Make quotes and verses italic
(setq org-fontify-quote-and-verse-blocks t)
#+end_src

*** Line length/spacing

#+begin_src emacs-lisp
(setq-default fill-column 90)
(setq-default line-spacing *line-spacing*)
#+end_src

*** Underline

Underline at a descent position, not baseline position.

#+begin_src emacs-lisp
(setq x-underline-at-descent-line t)
#+end_src

*** Mixed Pitch
In some modes (like ~org-mode~), we would like to use mixed pitch. To do this, we
need to add a hook that runs /after/ the UI is initialized.

#+begin_src emacs-lisp :tangle packages.el
(package! mixed-pitch)
#+end_src

#+begin_src emacs-lisp
(defvar mixed-pitch-modes '(org-mode LaTeX-mode markdown-mode gfm-mode Info-mode)
    "Modes that `mixed-pitch-mode' should be enabled in, but only after UI initialisation.")

(defun init-mixed-pitch-h ()
    "Hook `mixed-pitch-mode' into each mode in `mixed-pitch-modes'.
Also immediately enables `mixed-pitch-modes' if currently in one of those."
    (when (memq major-mode mixed-pitch-modes)
        (mixed-pitch-mode 1))
    (dolist (hook mixed-pitch-modes)
        (add-hook (intern (concat (symbol-name hook) "-hook")) #'mixed-pitch-mode)))

(add-hook 'doom-init-ui-hook #'init-mixed-pitch-h)
(add-hook 'org-mode-hook #'+org-pretty-mode)
#+end_src

** Layout
*** Frame

See Frame Layout documentation for details and terminology.

- Add some padding around the whole window (~internal-border-width~) to provide
  some air.
- Remove GUI elements.
- Make the title-bar transparent on macOS.

#+begin_src emacs-lisp
(when *is-macos*
  (setq frame-title-format nil)
  (dolist (filter '((ns-transparent-titlebar . t)
                    (ns-appearance . unbound)))
    (cl-pushnew filter default-frame-alist :test #'equal)))
#+end_src

*** Padding

Add margins inside windows to make text fell less crowded. Padding around the frame
is configured via the ~internal-border-width~ in the Frame section.

#+begin_src emacs-lisp
(setq-default left-margin-width 1
              right-margin-width 1)
#+end_src

** Interface
*** Number line
#+begin_src emacs-lisp
(setq display-line-numbers-type 'visual)
#+end_src

*** Disable =hl-line-mode=

#+begin_src emacs-lisp
(setq global-hl-line-mode '())
#+end_src

** Theme
*** =font-lock= faces customization
The default faces for =doom-horizon= is nice, but we need to change a few things.

Beginning with documentation and comments, they should be in italics.
#+begin_src emacs-lisp
(custom-theme-set-faces! 'doom-horizon
  `(font-lock-doc-face
    :slant italic
    :foreground ,(doom-color 'doc-comments))
  `(font-lock-comment-face
    :slant italic
    :foreground ,(doom-color 'comments)))
#+end_src

Now some tokens.
#+begin_src emacs-lisp
(custom-theme-set-faces! 'doom-horizon
  `(font-lock-string-face
    :foreground ,(doom-darken (doom-color 'green) 0.1))
  `(font-lock-variable-name-face
    :foreground ,(doom-color 'fg))
  ;; We will need to adjust the & operator later in the Tree-Sitter config.
  `(tree-sitter-hl-face:operator
    :foreground ,(doom-color 'fg))
      )
#+end_src

*** Enable theme
Now we can set the theme.

#+begin_src emacs-lisp
(setq doom-theme 'doom-horizon)
(remove-hook 'window-setup-hook #'doom-init-theme-h)
(add-hook 'after-init-hook #'doom-init-theme-h 'append)
(delq! t custom-theme-load-path)
#+end_src

** Org
There is a bunch of stuff here, so let's get going!

*** Symbols
Replace some commands and checkboxes with Unicode stuff :blush:

#+begin_src emacs-lisp
(appendq! +ligatures-extra-symbols
          `(:checkbox      "☐"
            :pending       "◼"
            :checkedbox    "☑"
            :list_property "∷"
            :em_dash       "—"
            :ellipses      "…"
            :arrow_right   "→"
            :arrow_left    "←"
            :title         "𝙏"
            :subtitle      "𝙩"
            :author        "𝘼"
            :date          "𝘿"
            :property      "☸"
            :options       "⌥"
            :startup       "⏻"
            :macro         "𝓜"
            :html_head     "🅷"
            :html          "🅗"
            :latex_class   "🄻"
            :latex_header  "🅻"
            :beamer_header "🅑"
            :latex         "🅛"
            :attr_latex    "🄛"
            :attr_html     "🄗"
            :attr_org      "⒪"
            :begin_quote   "❝"
            :end_quote     "❞"
            :caption       "☰"
            :header        "›"
            :results       "🠶"
            :begin_export  "⏩"
            :end_export    "⏪"
            :properties    "⚙"
            :end           "∎"
            :priority_a   ,(propertize "⚑" 'face 'all-the-icons-red)
            :priority_b   ,(propertize "⬆" 'face 'all-the-icons-orange)
            :priority_c   ,(propertize "■" 'face 'all-the-icons-yellow)
            :priority_d   ,(propertize "⬇" 'face 'all-the-icons-green)
            :priority_e   ,(propertize "❓" 'face 'all-the-icons-blue)))
(set-ligatures! 'org-mode
  :merge t
  :checkbox      "[ ]"
  :pending       "[-]"
  :checkedbox    "[X]"
  :list_property "::"
  :em_dash       "---"
  :ellipsis      "..."
  :arrow_right   "->"
  :arrow_left    "<-"
  :title         "#+title:"
  :subtitle      "#+subtitle:"
  :author        "#+author:"
  :date          "#+date:"
  :property      "#+property:"
  :options       "#+options:"
  :startup       "#+startup:"
  :macro         "#+macro:"
  :html_head     "#+html_head:"
  :html          "#+html:"
  :latex_class   "#+latex_class:"
  :latex_header  "#+latex_header:"
  :beamer_header "#+beamer_header:"
  :latex         "#+latex:"
  :attr_latex    "#+attr_latex:"
  :attr_html     "#+attr_html:"
  :attr_org      "#+attr_org:"
  :begin_quote   "#+begin_quote"
  :end_quote     "#+end_quote"
  :caption       "#+caption:"
  :header        "#+header:"
  :begin_export  "#+begin_export"
  :end_export    "#+end_export"
  :results       "#+RESULTS:"
  :property      ":PROPERTIES:"
  :end           ":END:"
  :priority_a    "[#A]"
  :priority_b    "[#B]"
  :priority_c    "[#C]"
  :priority_d    "[#D]"
  :priority_e    "[#E]")
(plist-put +ligatures-extra-symbols :name "⁍")
#+end_src

*** Remove =hl-line-mode=

With our current mixed pitch setup for =org-mode=, having the line highlighting
looks weird, so we need to disable it.

#+begin_src emacs-lisp
(add-hook! 'org-mode-hook (hl-line-mode -1))
#+end_src

** Splash Screen
Emacs can render an image as the splash screen, I kindly /borrowed/ the custom Emacs E
from [[https://tecosaur.github.io/emacs-config/config.html#splash-screen][@tecosaur]]'s configuration :speak-no-evil:.

Just make it theme-appropriate and follow the frame size. One thing that I needed
to change in the original configuration is that the SVG wasn't scaling properly.

#+begin_src emacs-lisp
(defvar fancy-splash-image-template
  (expand-file-name "misc/splash-images/emacs-e-template.svg" doom-private-dir)
  "Default template svg used for the splash image, with substitutions from ")

(defvar fancy-splash-sizes
  `((:height 300 :min-height 50 :padding (0 . 2))
    (:height 250 :min-height 42 :padding (2 . 4))
    (:height 200 :min-height 35 :padding (3 . 3))
    (:height 150 :min-height 28 :padding (3 . 3))
    (:height 100 :min-height 20 :padding (2 . 2))
    (:height 75  :min-height 15 :padding (2 . 1))
    (:height 50  :min-height 10 :padding (1 . 0))
    (:height 1   :min-height 0  :padding (0 . 0)))
  "list of plists with the following properties
  :height the height of the image
  :min-height minimum `frame-height' for image
  :padding `+doom-dashboard-banner-padding' (top . bottom) to apply
  :template non-default template file
  :file file to use instead of template")

(defvar fancy-splash-template-colours
  '(("$colour1" . keywords) ("$colour2" . type) ("$colour3" . base5) ("$colour4" . base8))
  "list of colour-replacement alists of the form (\"$placeholder\" . 'theme-colour) which applied the template")

(unless (file-exists-p (expand-file-name "theme-splashes" doom-cache-dir))
  (make-directory (expand-file-name "theme-splashes" doom-cache-dir) t))

(defun fancy-splash-filename (theme-name height)
  (expand-file-name (concat (file-name-as-directory "theme-splashes")
                            theme-name
                            "-" (number-to-string height) ".svg")
                    doom-cache-dir))

(defun fancy-splash-clear-cache ()
  "Delete all cached fancy splash images"
  (interactive)
  (delete-directory (expand-file-name "theme-splashes" doom-cache-dir) t)
  (message "Cache cleared!"))

(defun fancy-splash-viewbox-size (height)
  "Compute the size necessary to fit the image with height HEIGHT."
  (let ((vb-width (ceiling (* 0.80378 (float height))))
        (vb-height (+ height 7)))
    (message "vb-width: %s" (type-of vb-width))
    (message "vb-height: %s" (type-of vb-height))
    `(("$vbWidth" . ,vb-width) ("$vbHeight" . ,vb-height))))

(defun fancy-splash-generate-image (template height)
  "Read TEMPLATE and create an image if HEIGHT with colour substitutions as
   described by `fancy-splash-template-colours' for the current theme"
  (with-temp-buffer
    (insert-file-contents template)
    (re-search-forward "$height" nil t)
    (replace-match (number-to-string height) nil nil)
    (goto-char (point-min))
    (re-search-forward "$scale" nil t)
    (replace-match (number-to-string (/ height 107)) nil nil)
    (dolist (substitution fancy-splash-template-colours)
      (goto-char (point-min))
      (while (re-search-forward (car substitution) nil t)
        (replace-match (doom-color (cdr substitution)) nil nil)))
    (write-region nil nil
                  (fancy-splash-filename (symbol-name doom-theme) height) nil nil)))

(defun fancy-splash-generate-images ()
  "Perform `fancy-splash-generate-image' in bulk"
  (dolist (size fancy-splash-sizes)
    (unless (plist-get size :file)
      (fancy-splash-generate-image (or (plist-get size :template)
                                       fancy-splash-image-template)
                                   (plist-get size :height)))))

(defun ensure-theme-splash-images-exist (&optional height)
  (unless (file-exists-p (fancy-splash-filename
                          (symbol-name doom-theme)
                          (or height
                              (plist-get (car fancy-splash-sizes) :height))))
    (fancy-splash-generate-images)))

(defun get-appropriate-splash ()
  (let ((height (frame-height)))
    (cl-some (lambda (size) (when (>= height (plist-get size :min-height)) size))
             fancy-splash-sizes)))

(setq fancy-splash-last-size nil)
(setq fancy-splash-last-theme nil)
(defun set-appropriate-splash (&rest _)
  (let ((appropriate-image (get-appropriate-splash)))
    (unless (and (equal appropriate-image fancy-splash-last-size)
                 (equal doom-theme fancy-splash-last-theme)))
    (unless (plist-get appropriate-image :file)
      (ensure-theme-splash-images-exist (plist-get appropriate-image :height)))
    (setq fancy-splash-image
          (or (plist-get appropriate-image :file)
              (fancy-splash-filename (symbol-name doom-theme) (plist-get appropriate-image :height))))
    (setq +doom-dashboard-banner-padding (plist-get appropriate-image :padding))
    (setq fancy-splash-last-size appropriate-image)
    (setq fancy-splash-last-theme doom-theme)
    (+doom-dashboard-reload)))

(add-hook 'window-size-change-functions #'set-appropriate-splash)
(add-hook 'doom-load-theme-hook #'set-appropriate-splash)
#+end_src

I really don't use the dashboard commands, so let's remove them! While we're at it,
let's also remove the modeline, ~hl-line-mode~, and the cursor.

#+begin_src emacs-lisp
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-shortmenu)
(add-hook! '+doom-dashboard-mode-hook (hide-mode-line-mode) (hl-line-mode -1))
(setq-hook! '+doom-dashboard-mode-hook evil-normal-state-cursor (list nil))
#+end_src

Following our borrowing strategy, let's also add a phrase to the dashboard.

#+begin_src emacs-lisp
(defvar splash-phrase-source-folder
  (expand-file-name "misc/splash-phrases" doom-private-dir)
  "A folder of text files with a fun phrase on each line.")

(defvar splash-phrase-sources
  (let* ((files (directory-files splash-phrase-source-folder nil "\\.txt\\'"))
         (sets (delete-dups (mapcar
                             (lambda (file)
                               (replace-regexp-in-string "\\(?:-[0-9]+-\\w+\\)?\\.txt" "" file))
                             files))))
    (mapcar (lambda (sset)
              (cons sset
                    (delq nil (mapcar
                               (lambda (file)
                                 (when (string-match-p (regexp-quote sset) file)
                                   file))
                               files))))
            sets))
  "A list of cons giving the phrase set name, and a list of files which contain phrase components.")

(defvar splash-phrase-set
  (nth (random (length splash-phrase-sources)) (mapcar #'car splash-phrase-sources))
  "The default phrase set. See `splash-phrase-sources'.")

(defun splase-phrase-set-random-set ()
  "Set a new random splash phrase set."
  (interactive)
  (setq splash-phrase-set
        (nth (random (1- (length splash-phrase-sources)))
             (cl-set-difference (mapcar #'car splash-phrase-sources) (list splash-phrase-set))))
  (+doom-dashboard-reload t))

(defvar splase-phrase--cache nil)

(defun splash-phrase-get-from-file (file)
  "Fetch a random line from FILE."
  (let ((lines (or (cdr (assoc file splase-phrase--cache))
                   (cdar (push (cons file
                                     (with-temp-buffer
                                       (insert-file-contents (expand-file-name file splash-phrase-source-folder))
                                       (split-string (string-trim (buffer-string)) "\n")))
                               splase-phrase--cache)))))
    (nth (random (length lines)) lines)))

(defun splash-phrase (&optional set)
  "Construct a splash phrase from SET. See `splash-phrase-sources'."
  (mapconcat
   #'splash-phrase-get-from-file
   (cdr (assoc (or set splash-phrase-set) splash-phrase-sources))
   " "))

(defun doom-dashboard-phrase ()
  "Get a splash phrase, flow it over multiple lines as needed, and make fontify it."
  (mapconcat
   (lambda (line)
     (+doom-dashboard--center
      +doom-dashboard--width
      (with-temp-buffer
        (insert-text-button
         line
         'action
         (lambda (_) (+doom-dashboard-reload t))
         'face 'doom-dashboard-menu-title
         'mouse-face 'doom-dashboard-menu-title
         'help-echo "Random phrase"
         'follow-link t)
        (buffer-string))))
   (split-string
    (with-temp-buffer
      (insert (splash-phrase))
      (setq fill-column (min 70 (/ (* 2 (window-width)) 3)))
      (fill-region (point-min) (point-max))
      (buffer-string))
    "\n")
   "\n"))

(defadvice! doom-dashboard-widget-loaded-with-phrase ()
  :override #'doom-dashboard-widget-loaded
  (setq line-spacing 0.2)
  (insert
   "\n"
   (doom-dashboard-phrase)
   "\n"))
#+end_src

** Popup rules

#+begin_src emacs-lisp
(set-popup-rules!
  '(("^\\*info\\*"
     :slot 2 :side left :width 83 :quit nil)
    ("^\\*\\(?:Wo\\)?Man "
     :vslot -6 :size 0.45 :select t :quit nil :ttl 0)
    ("^\\*ielm\\*$"
     :vslot 2 :size 0.4 :quit nil :ttl nil)
    ("^\\*Ilist\\*$"
     :slot 2 :side left :size 0.3 :quit nil :ttl nil)
    ;; `help-mode', `helpful-mode'
    ("^\\*[Hh]elp"
     :slot 2 :vslot -8 :size 0.45 :select t)
    ("^\\*Checkdoc Status\\*$"
     :vslot -2 :select ignore :quit t :ttl 0)
    ("^\\*\\(?:[Cc]ompil\\(?:ation\\|e-Log\\)\\|Messages\\)"
     :slot -2 :size 0.45 :side right :autosave t :quit current :ttl nil
     :modeline t)
    ("^ \\*\\(?:undo-tree\\|vundo tree\\)\\*"
     :slot 2 :side left :size 20 :select t :quit t)
    ("^\\*\\(?:doom \\|Pp E\\)"  ; transient buffers (no interaction required)
     :vslot -3 :size +popup-shrink-to-fit :autosave t :select ignore :quit t :ttl 0)
    ("^\\*Backtrace" :vslot 99 :size 0.4 :quit nil)
    ("^\\*\\(?:Proced\\|timer-list\\|Process List\\|Abbrevs\\|Output\\|Occur\\|unsent mail\\)\\*" :ignore t)
    ("^\\*Flycheck errors\\*$"
     :vslot -2 :select t :quit t :ttl 0)))
#+end_src


* Languages
** Protocol Buffers

** Rust
*** Rust-Analyzer config
**** Fix =rustic-mode= not allowing configuring =initializationOptions=
Fix for =rustic-mode#105=.

#+begin_src emacs-lisp
(defun my--rustic-setup-eglot ()
  "Configure eglot for rustic."
  (require 'eglot)
  (add-to-list 'eglot-server-programs
               (append '((rustic-mode :language-id "rust") eglot-rust-analyzer)
                       rustic-analyzer-command
                       (:initializationOptions
                        (lambda (_) (plist-get eglot-workspace-configuration :rust-analyzer))))))

(after! rustic-lsp
  (advice-add 'rustic-mode-setup-eglot :override 'my--rustic-setup-eglot))
#+end_src

* Tools
** Bazel
*** =bazel-mode=
It has awesome Emacs support with =bazel-mode=, let's install it.

#+begin_src emacs-lisp :tangle packages.el
(package! bazel
          :recipe (:host github
                   :repo "bazelbuild/emacs-bazel-mode"
                   :files ("bazel.el")))
#+end_src

Now we configure it.

#+begin_src emacs-lisp
(use-package! bazel
  :config
  (setq bazel-buildifier-before-save t
        bazel-fix-visibility 'ask))
#+end_src

** Magit
*** Fix =emacsql= recipe

#+begin_src emacs-lisp :tangle packages.el
(package! emacsql :recipe (:host github :repo "magit/emacsql" :branch "main"))
#+end_src

*** Granular diffs

#+begin_src emacs-lisp
(after! magit
  (setq magit-diff-refine-hunk 'all))
#+end_src

*** Use =delta= for diff highlighting

#+begin_src emacs-lisp :tangle packages.el
(package! magit-delta)
#+end_src

#+begin_src emacs-lisp
(use-package magit-delta
  :hook (magit-mode . magit-delta-mode)
  :config
  (setq magit-delta-delta-args (append magit-delta-delta-args '("--no-gitconfig"))))
#+end_src

